<?php
/**
 * Database connection settings.
 *
 * The defaults match a stock WampServer install, so a fresh checkout connects
 * without editing anything.
 *
 * To use different credentials, do NOT edit this file — create
 * config/database.local.php (git-ignored) returning only the keys you want to
 * override, or set the DB_* environment variables. That keeps real credentials
 * out of the repository.
 *
 *     <?php  // config/database.local.php
 *     return ['username' => 'jolu', 'password' => 'secret'];
 */

declare(strict_types=1);

$settings = [
    'host'     => '127.0.0.1',
    'port'     => 3306,
    'database' => 'jolu',
    'username' => 'root',
    'password' => '',
    'charset'  => 'utf8mb4',
];

$local = __DIR__ . '/database.local.php';
if (is_file($local)) {
    $settings = array_replace($settings, (array) require $local);
}

foreach ([
    'DB_HOST' => 'host',
    'DB_PORT' => 'port',
    'DB_NAME' => 'database',
    'DB_USER' => 'username',
    'DB_PASSWORD' => 'password',
] as $variable => $key) {
    $value = getenv($variable);
    if ($value !== false && $value !== '') {
        $settings[$key] = $value;
    }
}

return $settings;
