name: Update WAMP

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: self-hosted

    permissions:
      contents: read

    steps:
      - name: Update WAMP project
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "C:/wamp64/www/JoLu"
          set GIT_TERMINAL_PROMPT=0
          git -C "C:\wamp64\www\JoLu" -c http.extraheader="AUTHORIZATION: bearer %GITHUB_TOKEN%" fetch origin
          git -C "C:\wamp64\www\JoLu" reset --hard origin/main
