name: Update WAMP

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: self-hosted

    steps:
      - name: Update WAMP project
        shell: cmd
        run: |
          git config --global --add safe.directory "C:/wamp64/www/JoLu"
          git -C "C:\wamp64\www\JoLu" fetch origin
          git -C "C:\wamp64\www\JoLu" reset --hard origin/main
